name: telegram_drive
description: A Flutter app with a Google Drive-like interface using Telegram for storage.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^10.1.9
  cached_network_image: ^3.3.1
  flutter_pdfview: ^1.3.2
  html: ^0.15.6
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  telegram_login_flutter: ^1.0.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  http_parser: ^4.1.2
  path: ^1.9.1
  mime: ^2.0.0
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^29.2.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cloud animations.gif